interface=wifi_int
driver=nl80211
ssid=<SSID>

# 2.4GHz band (a for 5GHz)
hw_mode=g

channel=1
# limit the frequencies used to those allowed in the country
ieee80211d=1

country_code=US
ieee80211n=1

# 802.11ac support
#ieee80211ac=1

# Wi-Fi multimedia
wmm_enabled=1

# WPA3 only
auth_algs=1
ieee80211w=2
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
wpa_passphrase=<PASSPHRASE>
