# Networking
interface=wifi_int
bind-interfaces
listen-address=127.0.0.1,10.0.0.1

# DNS Logic
port=53
domain-needed
bogus-priv

# Quad9
server=9.9.9.9
server=149.112.112.112

# DHCP Pool (Lease IPs .10 through .100)
dhcp-range=10.0.0.10,10.0.0.255,255.255.255.0,12h

# DHCP Options
# 3 = Default Gateway (This machine)
# 6 = DNS Server (Telling clients to ask this machine)
dhcp-option=3,10.0.0.1
dhcp-option=6,10.0.0.1
